INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('Illinois State University', true, 'Normal, IL', '', 'https://illinoisstate.edu/');
INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('Michigan State University', NULL, 'East Lansing, MI', NULL, 'http://www.msuspartans.com/');
INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('Indiana University', NULL, 'Bloomingtion, IN', NULL, 'https://www.indiana.edu/');
INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('University of Maryland', NULL, 'College Park, MA', NULL, 'https://www.umd.edu/');
INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('University of Michigan', NULL, 'Ann Arbor, MI', NULL, 'https://www.umich.edu/');
INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('Ohio State University', NULL, 'Columbus, OH', NULL, 'https://www.osu.edu/');
INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('Pennsylvania State University', NULL, 'University Park, PA', NULL, 'http://www.psu.edu/');
INSERT INTO ITKSTU.UNIVERSITY (UNIVERSITYNAME, HIGHLIGHTED, LOCATION, DESCRIPTION, LINKADDRESS) 
	VALUES ('Rutgers University', NULL, 'New Brunswick, NJ', NULL, 'http://www.rutgers.edu/');
